# Generated by Django 3.1.3 on 2023-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPublicacion',
            fields=[
                ('id_estpub', models.IntegerField(db_column='id_estpub', primary_key=True, serialize=False)),
                ('nombre_estpub', models.CharField(db_column='nombre_estpub', max_length=30)),
            ],
        ),
    ]
