# Generated by Django 4.2.1 on 2023-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTrabajo',
            fields=[
                ('id_categtrabajo', models.IntegerField(db_column='id_categtrabajo', primary_key=True, serialize=False)),
                ('nombre_categtrabajo', models.CharField(db_column='nombre_categtrabajo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(db_column='id_contacto', primary_key=True, serialize=False)),
                ('correo', models.CharField(db_column='correo', max_length=100)),
                ('telefono', models.IntegerField(db_column='telefono')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(db_column='id_material', primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(db_column='nombre_material', max_length=80)),
            ],
        ),
    ]
