# Generated by Django 4.2.1 on 2023-06-24 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0002_alter_publicacion_fecha_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(db_column='fecha_solicitud')),
                ('descripcion_solicitud', models.CharField(db_column='descripcion_solicitud', max_length=500)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
