# Generated by Django 3.1.3 on 2023-06-07 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dvrun',
            new_name='dv_run',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='appaterno',
            new_name='second_last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='appmaterno',
            new_name='second_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pnombre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='snombre',
        ),
    ]
